/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package huffman.example;

import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;

import huffman.Huffman;

public class App {
    public static void main(String[] args) throws IOException {
        String contents = new String(
                Files.readAllBytes(Paths.get(System.getProperty("user.dir") +
                        "/src/main/resources/test.txt")),
                StandardCharsets.UTF_8);

        Huffman.Encoded encoded = Huffman.encode(contents);
        PrintWriter writer = new PrintWriter(
                new FileWriter(System.getProperty("user.dir") +
                        "/src/main/resources/compressed.hm"));
        writer.write(encoded.encoded);

        writer.close();
    }
}
