/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lob;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void lob() {
        LOB lob = new LOB();
        // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
